version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
        - ./FreshRSS/:/var/www/FreshRSS/data
        - ./FreshRSS/:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Madrid
      CRON_MIN: '3,33'
   
    ports:
      - "2004:80"

